### ISSUE TITLE
Error: nrow(w) == g is not TRUE

### ISSUE THREAD

**Issue by jasonvrogers** [denisagniel/tcgsaseq#1]
Hi, I've been trying to use tcgsa-seq to apply a regression framework to GO enrichment in my data. The manual seemed clear enough, but I set up a test run for my data and I simply can't get it to work and I have no idea where the error is coming from.

The code is 

test <- varseq(exprmat=log2(tpms2), 
covariates=as.matrix(designMat[,1]), 
variables2test=as.matrix(designMat[,2]),
preprocessed=TRUE)

Computing the weights... Done!
Error: nrow(w) == g is not TRUE

My exprmat is a 5823 x 47 matrix of absolute TPM values.
My covariates variable is a 47 x 1 matrix of 1s
My variables2test is a 47 x 1 matrix of a mix of 1s and 0s.

I can attach the TPM table if that's helpful, any thoughts on where the error is coming from?
Also, in the documentation it was unclear why we effectively have to specify a design matrix twice... once with the variables we are not testing, and again with the variables we are testing. Can you give some insight into that (as opposed to specifying a design matrix and telling it to regress on columns 3 and 5, for example).

Thanks!

**Comment by borishejblum** [comment]
Hi Jason,

First thank you for your interest in our work and in tcgsaseq. Below are a few remarks in repsonse to your message.

1) I think I was able to reproduce your error, this was likely due to the introduction of `NaN` values by the `log2` function applied to `0` tpm values... The latest commit should address this issue, you can install it with the following commands:
`install.packages("devtools")`
`devtools::install_github("denisagniel/tcgsaseq")`
Let me know how it goes.

2) Specifying the two matrices separately is not different than specifying a design matrices and telling it which columns should be tested. It is simply the way the package is implemented at the moment, this may change to become more user friendly in the future.

3) If you want to perfrom Gene Set Analysis, you should probably use the `tcgsa_seq` wrapper function, rather than `varseq`which is the wrapper for gene by gene analysis.

Let me know if that does not help.

Happy holydays,
Boris

**Comment by jasonvrogers** [comment]
Hi Boris,

Thanks for much for helping!

I actually did not have any 0s in my TPM matrix. However, I did have a floor set such that all TPMs below 1 were floored at a TPM value of 1. I suspect this screwed up the mean variance relationship since the variance became 0 at that value. I tried again with unfloored data and it worked better. I also tried again with the raw count matrix and it also worked fine.

Thanks again,
Jason
